export const CONNECT_WALLET = 'CONNECT_WALLET'
export const LOAD_NETWORK = 'LOAD_NETWORK'
export const NETWORK_CHANGE = 'NETWORK_CHANGE'
export const WALLET_FOUND = 'WALLET_FOUND'
export const WALLET_DISCONNECT = 'WALLET_DISCONNECT'
export const LOAD_DASHBOARD = 'LOAD_DASHBOARD'
export const DASHBOARD_LOADING = 'DASHBOARD_LOADING'

